version: "2"

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - unused
    - errcheck
    - rowserrcheck
    - sqlclosecheck
    - noctx
    - ineffassign
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck


formatters:
  enable:
    - goimports
